>tig00000002_arrow__1 [63543 64217] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFDASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00000083_arrow__1 [15638 16312] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDNTAGFELFSFMDGFLGYNQILMSEDDKEKMAFI
TPWGVFHYKVMPFGLKNAGSTYQRAIVTLFHDMMHKEIEVYV-----DDMIAKIRRRKDH
VETLTKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00000113_arrow__1 [177685 177098] 
LDARIIYPISDSS-VSPVQVVSKKGGMTV-KNDNNELIPIKTVIGWCVCMDYR-------
-----KLNDATR-KDHFPLQFID-MLERLAGHEFYYFLDGYLRYN-IPIAPEDKEKTTFT
CPYGTFAFKRMPFGLCNAPVTFQRCMMAIFSNMVEKYIEIFM-----DDYSVFGSSFDSC
LNNLVLVLQRCEETNLVLNWEKCHFRVKEGIVLD--------------------------
----------------------
>tig00000131_arrow__1 [82291 81617] 
-EVGFIEVSQYFDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00000289_arrow__1 [50425 49751] 
-EVGFIEVSQYSDWVANIVPVIKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00000494_arrow__1 [78540 79205] 
----FIEVAHYADWIANVVPVMKND------------------GRVRVCVGYR-------
-----NLNRASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSSYNQIRMRKEDRSKTSFI
TPWGTFCYKVMLFGLKNAGATYQRAMVALFHDMMHNEIEVYV-----DDMIAKSRPGEDH
VAILRKLFERLRKYQLRLNLAKCVFGARSEKLLGFMVSSRGIEIDPSKVKAICDLRPPSS
VREVRSLLGRLNYVARFISQLS
>tig00000505_arrow__1 [33165 33779] 
---------------------------------------TCITTGWRVCIDYC-------
-----KLNAATK-KDHFPLSSID-ILEMLAGQSYFCFLDGYSGYNQVPVCSEDQGKTTFT
CPFGTFAFRRMPFGLCNAPATFQRCMMAVFLDMVGEFLEVFM-----DHFSVFGSSFHIC
LQNLRRVLQRCMEVNLILSWEKSHFMV-QGIVLGHIVLQHGLEVDP-KIELIKKLPPPNS
VKQVRSFLGHAGFYRRFIPSFS
>tig00000508_arrow__1 [84979 84305] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVVGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00000634_arrow__1 [44402 44061] 
LKVGFIEVIPYLEWVVNIVPIIKKD------------------GKVRVCVDYR-------
-----DLNKASP-KDDFSLPHIDVLVDSTLSFELFSFIDVFSRYNQILLKEEDKAKTFFI
TPWGTFCYKVILFGLKNAGATYKL------------------------------------
------------------------------------------------------------
----------------------
>tig00000643_arrow__1 [23795 23130] 
-DVGFIEVTQYATWVSNIVLVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLIDSTAGFELFSFMDGFSGYNQILMNEEDKEKMAFT
TPWGVFHYKVMLFGLKNVGATYQQAMVTLFHDMMHKEIEVYV-----DDMIAKTRRGENH
VEILMKLFDRLRKFRMRLNRAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAIRELKPPST
VKEVRSLMDRLNYIARFIS---
>tig00000644_arrow__1 [19233 19796] 
----FIEVAHYTNWIANVVPVMKKD------------------GRVKVCVDYR-------
-----DSNRVSP-KDDFPLPYIDMLVNSIAGFEMFSFMDSFSSYNQI-MREEDRSKTSFI
TP-ATFCYKVMPFGLKNAGATYERAMVTLFHDMMHNEIEVYV-----DDMIAKSRPGEDY
VAILRKLFERLCKYQLRLNPAKCVFRAKSGELLGFMVSSRGIEIDPSR------------
----------------------
>tig00000696_arrow__1 [39080 38409] 
--VGFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFI
TPWGTFCYRVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQFS
>tig00000768_arrow__1 [40959 41633] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNTEATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAIYEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00000787_arrow__1 [117538 116963] 
----------------------KKGGMTIQKNDSNELIPTRTVTGWRVCMDYR-------
-----KLNDATR-KDHFPLPFIDQMLERLAGHEFYCFLDGYSGYNQIPIAPKDQEKTTFT
CPYGTFAFRRMLFGLCNAPATFQRCVMAIFSDMVEKYIEVFM-----DDFSIFGSSFDSC
LNNLALVLQRCEETNLVLNWEKCHFMVQEEIVLGHKISENGIEVDRAKVEVM--------
----------------------
>tig00000794_arrow__1 [36220 36891] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQL-
>tig00000886_arrow__1 [113114 112440] 
-NKGFIEVIPYADWIANIIPVMKKD------------------NKVRICIDYR-------
-----DLNKANP-KDDFSLPHIDVLVDNTAGFELFLFMDRFFGYNQILMKEEDKTKTSFI
TLWGTFCYRVMPFGLKNDGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPDKCVFGARSGKLLGFVVSSHGIKVDPSKIKAIRYICTPTS
VKEVRSLLGRLNYIARFISQLS
>tig00001010_arrow__1 [17103 16429] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHEEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00001014_arrow__1 [193740 193009] 
LDTGIIYPISDSS-VSPAHVVPKKGDMTIQKNDKNKLIPSKAVTGWRVCMDYR-------
-----KLNEATR-KDHFPLPFIDQMLERLAEHEFYCFLDGYSRYNQIPNASKDQEKTTFT
CPYDTFAFRRMPFGLCNAPAIFQRCMMAIFFYMVENYIEIFM-----DDFSVFGSSFDSC
LNNLALVLQKCEETNLILNWEKCHFMVQEGIVLGHKFSENGIDFNRAKVKVIAKSPPPTF
VKLVKGFLGHAGFYRRFIKDFS
>tig00001092_arrow__1 [33063 32386] 
FDVDFIEVTQYATWVANIVPVLKKD------------------GHVRVYVDYR-------
-----DLNKASP-KDDFPLPHINVLVDSTTGFELFSFMDDFSGYN-ILMNEEDKEKTAFT
TPWGVFHYKVMPFRLKNAGVTYQRVMVTLFHDMMHKEIEVYV-----DDMIAKTRHGEDH
METLTKLFDRLRKFRLRLNLTKCVFGASSGKLLGFIVSNKGIEIDSSKVKTICELKPPAT
VKEVRSLMGRLNYIARFIS-LS
>tig00001132_arrow__1 [119794 119120] 
-DVGFIEVT-YPGWVANIVSVLKKD------------------GRVRVCVDYH-------
-----DLNKASP-NDDFLLPHIDVLVDSTTVFELFSFMDGFSGYNQILMNEEDKEKTVFT
TPLGIFHYKVMHFGLKNVWATYQRAMVTLFHDMMHKEIKVYI-----DDMIAKTWRVEDH
VETLTKLFDRLWKFKLHRNPAKYVFGASSGKLLRFIVSNKGIEIDPSKLKAICELKPPTS
VNEVQSLMGRLNYITRFISQLS
>tig00001153_arrow__1 [40546 40151] 
------------------------------------------------------------
---------------------------------LFSFMDGFSGYNQILMKEEDKAKTLFI
TPWGTFCYKVMPFGLKNAGATY-RAMVALFHDMMHKEIEVYV-----DDMIAKSRHGEDH
ILVLKKLFERLRKYKLRLNPAKCVFEARSGKLLGFMVASRGIEIIPLRSK----------
----------------------
>tig00001169_arrow__1 [31480 32154] 
-DIEFIEVTQYPTWVANIVPILKKD------------------DRIWVCVVYR-------
-----DLNKVSP-KDDFPLPHIDILVDNTTGFELFSFMDGFSSYNQILMNEEGKEKTAFT
TPWGVFHYKVMPFGLKKAGATYQRAMVTLFHDMMHREIEVYV-----DDMIAKTRRGEDH
VETLMKLFERL-KFKLRLNPAKYVFDASSRKLLGFIVSNKGIEIDPSKMKAICELKPPTT
VKEVQGLMGKLNYIAGFISQLT
>tig00001280_arrow__1 [16250 15579] 
--VGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDGFPLPHIDVVVDSTARLELFSFMDGFSGYNQILMSEDDKEKTAFI
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMMHKEIEVYV-----DDMIAKTRRGKDH
VETLTKLFERLRKFKLRLNRVKCVFGASSGKLLGFIVSNKGIEIDPSKMKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00001357_arrow__1 [110984 110550] 
------------------------------------------------------------
------LNKANP-KDDFPLPHIDVLMDSIAGFELFSFMNGFSGYNQIRMKDDDK-KTAFI
TP-GTFHYKIMPFGLKNARATYQWAMVALFHDMMHKKLK-YMSTTCEDETQSESRG----
--TLMKLFNRPREFKLRLNPMQCVFGVSFGKLLSFIVN----------------------
----------------------
>tig00001400_arrow__1 [51471 51890] 
--VGFIEVIPYPKWVADIVLVMKKD------------------GKARVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSIADFKLFSFMDGFSGYNQILLEEEDKAKTSFI
TPWGTFCYKVMPFGLKNAWATYQRAMVALFHDMMHKEIEVYV-----DDMIAS-------
-----------------LNLEK--------------------------------------
----------------------
>tig00001417_arrow__1 [101124 100459] 
----FIEVSQYSDWVANIVSVMKKD------------------DRARVCVDYG-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSSYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLKFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00001445_arrow__1 [9200 8595] 
------------------------N------------------GQVRVCVDYR-------
-----DLNKASP-KDDFPLSHIDVWVDSMAGFELFLFMDGFSGYNQILLKEKDKAKTSSI
TS-GTLCYKVMPFGLKNAGVTYQRAIMALFHDMMHKEIEVYV-----DDMIAKSRPREDH
VQVLRKLFEWLQKYKLKFNPAKCIFGT-SGKILWFMVSNRGIEIDPSKIKEIRDIGTPTT
IKKVRSLLGRLNYIARFICQLS
>tig00001473_arrow__1 [40857 41528] 
--VGFFEVIPYPKWVANIFSVMKKD------------------GRVRICVDYH-------
-----DLNKASP-KDDFPLPHINILVDSTAGFELFSFMDGFSGYNQILLKEEDKAKMSSI
TP-GTFCYKVMTFGLKNIGAMYQRAIVALFHDMMHKEIEVYV-----DDMIAKSKSGEDQ
VQVLRKLFERLQKYKLKLNPAKCIFGARSGKLLGFIVSNQGIEIDPSKVKAILDIGTPII
VKEVRSLLARLNYSARFIYQLS
>tig00001490_arrow__1 [64760 64092] 
---GFIEAIPYADWIANIVLVMKKD------------------GKIQVCVDYR-------
-----DLNKASL-KDDFPLPHIDVPVDSTAGFELFSFMDGFSGYNQILMKEEDKAKTSFI
TPWGMFCYRVMPSGLKNVGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNLNKCVFRTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTI
VKEVRGLLGRLNYIARFISQLS
>tig00001606_arrow__1 [42014 41340] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00001748_arrow__1 [30673 31344] 
--VGFIEVIPYLEWVANIVPVMKKD------------------GRVRICVDYC-------
-----NLNKTSP-KDDFPLPHIDFLVDSTSGFELLSFMDEFFGYNQILLKEEDKVKTSFI
TPWDIFCYKVMPFGLKNAGSTYQRAMVALFHDMMHKEIEVYV-----DDMIAKSKSGEDH
VQVLRKLFERL-KYKLKLNLAKCIFGALR-KLLGFMVSNRGIEIDPSKVKAILDIGTPTT
VKEVRSLLGRLNYIARFFCQLS
>tig00001768_arrow__1 [11475 11768] 
------------------------------------------------------------
-------------PEGLPSP-THCLVDSTTGFELFSFMDGFSRYNQILLKEEDKAKTSFI
TPWGTFCYKIMPFGLKNAGATYQRAMVALFHDMMHKEIEIYV-----DDMIAKSK-----
------------------------------------------------------------
----------------------
>tig00001789_arrow__1 [49656 50327] 
--VGFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHNDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFI
TPWGTFCYRVMPFGLKNARATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFMVSNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00002028_arrow__1 [104004 104678] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDRIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00002294_arrow__1 [25764 26438] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRICIDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHKEIEVYV-----DDMIAKTRHGEDH
VETLTKLFERLRKFKLRLNPAKYVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPTT
VKEVRGLMGRLNYIVRFISQLS
>tig00021141_arrow__1 [1260994 1260326] 
---GFIEAIPYTDWIANIVPVMKKD------------------GKVRICVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKAKTSFI
TPWGTFCYRVMPFGLKNAGATYQRAMIALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGARSGKLLGFVVSSRGIEADPSKIKAIRDICTPTS
VKEVRSLLGRLNYIARFISQLS
>tig00021143_arrow__1 [2294995 2294264] 
LDAGIIYPISDSSWVSPVQVVPKKRGLTVQKNDNNELIPTRTVTGWCVCMDYR-------
-----KLNDATR-KDHFSLPFIDQMLERLARHEFYCFLDGYSGYNQIPITLEDQEKTTFT
CPYGTFAFRRIPFGLCNAPATFQRCMMAIFFYMVEKYIEIFM-----DDFSIFGSSFDSC
LNNLALVLQKCDETNLFLNWEKCHFMMQEEIVLEHKISENGIEVDRAKVEVIAKLPPPTS
VKLVRGFLWHAGFYRRFIKDFS
>tig00021151_arrow__1 [527013 527687] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRICVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHKEIEVYV-----DDMIVKTRHGEDH
VETLTKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00021153_arrow__1 [2503801 2503133] 
---GFIEAVPYADWIANVVPVMKKD------------------GRVRICVNYR-------
-----DLNRASL-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYN-ILMKEEDKAKTSFI
TPWGTFCYKVMPFGLKNARTTYQMAMVALFHDMMHKEIEVYV-----DDMIAKSRHGEDH
ILVLKKLFERLRKCRLKLNSAKCVFGARSGKLLGFVVASRGIEINPSKIKAIRDIRIPST
VKEVKGLLGRLNYITRFISQLS
>tig00021156_arrow__1 [1078880 1079554] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00021175_arrow__1 [3875375 3874707] 
---GFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKKEDKAKTSFI
IPWGTFCYRVMPFGLKDAGATYQRAMVALFHDMMHKEIEAYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNQGIKIDPAKIKAIREIRTPTT
VKEVKSLLGRLNYISRFISQLS
>tig00021177_arrow__1 [2298358 2297684] 
-NVGFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFT
TPWGTFCYRVMPFGLKNAGATYQRTMVALFHDMMRKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00021179_arrow__1 [672111 672782] 
--VGFIEVIPYSKWVANIIPVMKKD------------------GKVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVENITDFELFSFMDGFSGYNQILLKEEDKAKTSFI
TSWGTFCCKVMPFGLKNIGATYQRAMVALFHDMMHKEIKVYV-----DDMIAKSKIGEDH
VQVLRKLFERIRKYKLKLNPAKYIFGA-SGKLLGFMVSNREIEINLSKVKAILDIGIPTT
VKEVRSLLGRLNYIARFI-YLS
>tig00021182_arrow__1 [5589459 5588728] 
LDAGIIYPISDSS-VSPVQVVPKKGGMTVQKNDNNELIPTKTVTGWRVCMDYK-------
-----KLNDATR-KDYFPLPFIDQMLERLAGYEFYCFLDGYSGYNQISIAPEDQEKMTFS
CPYGTFAFRRMPFVLCNAPATIQRCMMAIFSNMVENYIEIFM-----DDFSIFGSSFDSC
LNNLALILQRCEETNLVLN-EKCHFMVQEGIVLGHKIFENGIEVDRAKVEVIAKLPPPTS
VKLVRGFLGHAGFYRRFIKDFS
>tig00021183_arrow__1 [44128 44715] 
LDARIIYPISDSS-VSPVQVVSKKGGMTV-KNDNNELIPIKTVIG-CVCMDYR-------
-----KLNDATR-KDHFPLQFID-MLERLAGHEFYYFLDGYLRYN-IPIAPEDKEKTTFT
CPYGTFAFKRMPLGLCNAPVTFQRCMMAIFSNMVEKYIEIFM-----DDYSVFGSSFDSC
LNNLVLVLQRCEETNLVLNWEKCHFRVKEGIVLD--------------------------
----------------------
>tig00021184_arrow__1 [14754 15341] 
LDARIIYPISDSS-VSPVQVVSKKGGMTV-KNDNNELIPIKTVIG-CVCMDYR-------
-----KLNDATR-KDHFPLQFID-MLERLAGHEFYYFLDGYLRYN-IPIAPEDKEKTTFT
CPYGTFAFKRMPLGLCNAPVTFQRCMMAIFSNMVEKYIEIFM-----DDYSVFGSSFDSC
LNNLVLVLQRCEETNLVLNWEKCHFRVKEGIVLD--------------------------
----------------------
>tig00021197_arrow__1 [2738548 2737874] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-MDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDGLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVWSLMGRLNYIARFISQLS
>tig00021205_arrow__1 [2423483 2423022] 
------------------------------------------------------------
-------------------------------------------YNQILIKEEDKAKTSFI
TP-GTFCYKVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYL-----DDMIAKSRHGKDH
ILVLKKLFERLRKYRLILNLAKYVFGARSGKLLGFVVASHGIEIDPSKIKAICDIKIPST
VKEVRSLLGRLNYIARFISQLS
>tig00021208_arrow__1 [8214229 8214897] 
---GFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKANP-KDDFPLPHINVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKISFI
TPWGTFCYRVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDSAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00021213_arrow__1 [2671408 2672079] 
--VGFIEVAHYADWVANVIPVMKKD------------------GRVRVCVDYR-------
-----DLNRVSP-KDNFPLPHIDVLVDSTAGFELFSFMDGFSGYNQIRMREVDIRKTSFI
TPWGTFCYKVMPFGLKNAGATYQRAMAALFHDMMHNEIKVYV-----DNMIAKSRPGEDH
VAILRKLFERLRKYQLRLNLAKCVFEAKSGKLLGFMVSSMGIEIDPSKVKAICHLRPPSS
IREVRSLLERLNYVARFISQLS
>tig00021220_arrow__1 [1205777 1205103] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEIRSLMGRLNYIARFISQLS
>tig00021223_arrow__1 [2581129 2581803] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGCNQILMNEENKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFNRLRKFKLRLNPTKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021225_arrow__1 [761163 760489] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TLWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRRENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRF
VKEVRSLMGRLNYIARFISQLS
>tig00021229_arrow__1 [4229088 4228414] 
-DVGFIEVTQYPTWVANTVPILKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMSEDDKEKTAFI
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHKKIEVYV-----DDMIAKTRRGKDH
VETLTKLFERLWKFKLSLNPAKCVFGASSGKLLGFIVSNRGIEIDPSKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00021236_arrow__1 [664034 664708] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGHRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021242_arrow__1 [1018449 1017775] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DNMIAKTRLGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLRFIVSSKGIEIDPFKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021261_arrow__1 [2642008 2641334] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GCVRVCMDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSSYNQILMSEDDKEKTAFI
TPWGVFHSKVMPFGLKNAGAMYQ-AMVTLFHDIMHKEIEVYV-----DDMIAKTRRRKDH
VETLTKLFERLRKFKLRLNPAKCVFGASLGKLLGFIVSNKGIEIDSSKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00021262_arrow__1 [243465 242791] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYC-------
-----DLNKASP-KDDFPPPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TLWGLFHYKVMSFGLRNAGATYQRAMVTLFHDMMHEEIEIYV-----DDMIAKTRCGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021264_arrow__1 [616421 616903] 
------------------------------------------------------------
-----------------------------------SFMDGFSEYNQILLKEKDKAKTSFI
TPWGTFIYKVMPFGLKNAGATYQRAMVALFHDIMHKEIEVYV-----DDMITKFRPGEDH
VLVLRKLFERL-KYKLKLNPAKCIFGARSGKLLGFMISNHGIEIDPSKIKAILEIGTPTT
VKEVRSLLGRLNYIARFICQL-
>tig00021266_arrow__1 [2358856 2358188] 
---GFIEAVPYADWIANVVLVMKKD------------------GRVRICVDYR-------
-----DLNRASP-KDDFMLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKAKTSFI
TPWGTFCYKVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRHGEDH
ILVLKKLFERLRKYKLRLNPAKCVFGARSGKLLGFVVASCGIEIDPSKIKAIRDIRIPST
VKEVRSLLGRLNYIARFISQLS
>tig00021274_arrow__1 [163197 163871] 
-EVGFIEVSQYSDWVANIVLVMKKD------------------GRVRVCVDYR-------
-----DLNKASL-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMAFGLRNARATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGKLNYIARFISQLS
>tig00021282_arrow__1 [447516 447052] 
------------------------------------------------------------
----------------------------------FFFLDGYSGYNQVLVCPEDQGKITFT
CPFGTFAFRQMPFRLCNAPATFQRYMMAIFSDMVREYMEVFM-----DDFSIFWSSFHVC
LQNLRKVLQRCIEANLILSWEKSHFMVHQGIVLGHILSQHDIEVDPAKIELIEKLPPPNS
VK-VRSFLGHAGFY--------
>tig00021284_arrow__1 [477939 478613] 
-EVGFIEVSQYPDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFAGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRVMVTLFHNMMHEEIEVYV-----DDMIAKTRRRKNH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDLSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021287_arrow__1 [168846 168172] 
-DVGFIEVTQYPTWVANIVIVLKKD------------------GRARICVDYR-------
-----DLNKASP-KDDFPLPHIHVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHKEIEVYV-----DDMIAKTRYREDH
VETLTKLFERLQKFKLRLNPTKCVFGAISGKLLGFIVSNKGIEIDPCKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00021294_arrow__1 [480103 479714] 
------------------------------------------------------------
------------------------------------------------------------
-----FCYKVMPFGLKNVGATYQRAMVALFHDMMHNEIEVYV-----DDMIAKSRPGEDH
VAILCKLFECLRKYQLHLNLAKCIFGAKSGKLLGFMVSSRGIEIDPSKVKAICDLRSPSS
VREVCSLLGWLNYVARFISQ--
>tig00021296_arrow__1 [737100 736432] 
---GFIEAVPYADWIANVVPIMKKD------------------GRVRICVDYR-------
-----DLNRASP-KDDFPLPHIDVLVDSTAGLELFSFMDGFLGYNQILMKEEDKAKTSFI
TPWGTFCYKVMPFGLKNAGETYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRHGEDH
ILVLKKLFERLRKYKLRLNPAKCVFEARSGKLLGFVVASRGIEIDPSKIKAIRDIRIPLT
VKEVRSLLGRLNYIA-FISQLS
>tig00021297_arrow__1 [16490 17164] 
-DVGFIEVT-YPGWVANIVSVLKKD------------------GRVRVCVDYH-------
-----DLNKASP-NDDFLLPHIDVLVDSTTVFELFSFMDGFSGYNQILMNEEDKEKTVFT
TPLGIFHYKVMHFGLKNVWATYQRAMVTLFHDMMHKEIKVYI-----DDMIAKTWRVEDH
VETLTKLFDRLWKFKLHRNPAKYVFGASSGKLLRFIVSNKGIEIDPSKLKAICELKPPTS
VNEVQSLMGRLNYITRFISQLS
>tig00021298_arrow__1 [31256 30582] 
-NMGFIEVSQYPDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFSLPHIIMLMDSTTGFELFSFMDGFLGYNQILMNEADKMKTTFI
TPWGTFHYKVVPFGLKNAGVTY-RAVVTLFHDMTHKEIEVYV-----NDMIAKIQQGEDH
VKILTKLFDRLWKFKLCLNLAK-VFGVALGKLLGFIMSSKGIKFDPSKVKAICQIKPPST
VKVVRSLMGKLNYIARFISQLS
>tig00021300_arrow__1 [207854 208333] 
------------------------------------------------------------
-----DLNKASP-KDDFPLPHIDVLVDSTVGFELFSFMDGFSGYNQILMKEEDKAKTSFI
TPWGTFCYRIMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKA---------
----------------------
>tig00021301_arrow__1 [20579 20049] 
------------------------------------------------------------
--------------------HINVLVDSIAGFELFSFMDGFSSYNQILMNEEDKKKMAFT
TPWGVFHYKVMPFGLKNARATYQRAMVTLFHDMIHKEIEVYV-----DDMIAKTRRGEDH
VETLTKLFNRLWKFRLRLNPAKCVFGASSGKLLRFIVSNKGIEIDPSKVKAIYELKPSAI
VKEVRSLMGRLNYIARFISQLS
>tig00021302_arrow__1 [2444113 2443448] 
----FIEVAHYADWIANVVPVMKND------------------GRVRVCVDYR-------
-----NLNRASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQIRMRKEDRSKTSFI
TPWGTFCYKVMLFGLKNAGATYQRAMVALFHDMMHNEIEVYV-----DDMIAKSRPGEDH
VAILRKLFERLRKYQLRLNLAKCVFGARSEKLLGFMVSSRGIEIDPSKVKAICDLRPPSS
VREVRSLLGRLTYVARFISQLS
>tig00021307_arrow__1 [747094 747765] 
--VGFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFI
TPWGMFCYRVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLWKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00021309_arrow__1 [1054007 1054678] 
--VGFIEAIPYADWIANIVPMMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFI
TPWGTFCYRIMPFGLKNAGATYQRAMVALFHDMIHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFMVSNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00021316_arrow__1 [182174 182848] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLMKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGKLNYIARFISQLS
>tig00021318_arrow__1 [1252503 1251838] 
---GFIEAIPYADWIANIVLVMKKD------------------GKIRVCVNYR-------
-----NLNKASP-NDDFPLPHIDVLVDSTAGFELFSFMNGFSGYNQILMKEEDKAKTSFI
TPWGTFCYRVMPFGLKNARATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSKPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VKEVRSLLGRLNYIARFISQL-
>tig00021326_arrow__1 [1329049 1328624] 
------------------------------------------------------------
-------------------------------------------------------KNVIY
HPWGLFHYKVMPFGLKNARATYQRAMITLFHDMMHEEIKVYI-----DDMIGKTRRGENH
VETLTKLFDRFRKFKLRLNPAKCVFEATSGKLLGFIVSSKGIKIDPSKVKAICEVKPPRF
VKEV-SLMGRLNYIARFISQLS
>tig00021330_arrow__1 [4641792 4642454] 
----FIEAIPYADWIVNIVPVMKKD------------------GKVRICVDYR-------
-----DLNKASL-KDDFPLPHIDVLVDSIAGFELFSFMDGFFGYNQILMKEEDKAKTSFI
TPWGTFCYRVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRLREDQ
ILVLRK-FERLRKYKLRLNPNKCVFTARSGKLLGFVVSSRGIEVDLSKIKAIRDICTPTS
VKEVRSLLGRLNYISRFISQLS
>tig00021339_arrow__1 [4296613 4297287] 
-DVKFIEVTQYPTWVANIVPVLKKD------------------GRVRICVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHKEIEVYV-----DDMIAKTRHGEDH
VETLTKLFERLQKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPTT
LKEVRGLMGRLNYIARFISQLS
>tig00021340_arrow__1 [461990 462664] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGVSSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00021342_arrow__1 [1982983 1982309] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRICVDYC-------
-----DLNKASL-KDDFPLPHIDVLMDSTAGFELFSFMDGFSGYNQILMNEEDKEKIAFT
TPWGVFHYKVMPFGLKNDGATYQRAMVTLFHDMMHREIEVYV-----DDMIAKTRHGEDH
VETLTKLFERLQKFKLRLNPTKCMFGAISGKLLGFIVNNKGIEIDPCKVKAICELKPPTT
VKEVWGLMGRLNYIARFISQLS
>tig00021345_arrow__1 [242421 241789] 
--VGFIEVIPYADWIANIISVMKKD------------------DKVRICIDYR-------
-----DLNKANP-KDDFSLPHIDVLVDSIAGFELFLFMDRFSGYNQILMKEEDKTKTSFI
TLWGTFCYRVMSFSLKNDGATYQRAMVALFHDMMHKEIEVYI-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPDKYVFGARSGKLLGFVVSSHGIKVDPAKIKAIRYICTPSS
VKEVRSLLG-------------
>tig00021376_arrow__1 [172551 171817] 
LIQGIIYPISDSAWVSPMQVVLKKGGMTVQPNDDNELIPTRIVTGWRVCIDYR-------
-----KLNDATH-KNHFPFLFID-MLEELAAAVLLFFRWIFMVIIKSLLHLRIKKKLLLH
CPFGTFAYRKMPFGLCNASATFQRCMMAVFSDMIEKYIEIFM-----DDFSIYSSSFDSC
LNNLALVLQRCEETNLILNWEKCHFMV-EGIVLGHKISMREIEVDRAKIEGISNCRL-LL
LRLVRGFLRDVGFYRCFIKYFS
>tig00021384_arrow__1 [309957 309286] 
--VGFIEAIPYADWIANIVPVMKKD------------------GKIRVCIDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKAKTSFI
TPWGTFYYRVMPFGLKNAGATYQRAMVALFRDMMHKKIEIYV-----DDMIAKSRPGEDY
ILVLRKLFERLQKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VKEVRSLLRRLNYIARFISQLS
>tig00021385_arrow__1 [562906 562241] 
----FIEVAHYSDWIANIILVIKKD------------------GRVRTCIDYR-------
-----DLNQASP-KDDSPLPHIDVLVNNTAGFELFSFMDGFSSYNQIHIKEEDSSKTSFI
TLWGTFCYKVMPFGLKNARATYQRAMVALFHDMMHKEIKVYV-----DDMITKSRPGEDH
VKILCKLFECLRKF-LCLNLTKCVFGVKSRKLLGFMVSSRGIEIDPSKVKAICELRPPTS
VKEVCSLLGRLNYVARFISQLS
>tig00021392_arrow__1 [1801280 1800609] 
--VGFIKVIPYTEWVANIVLVMKKD------------------GKVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFDLFSFMDGFSRYNQILLKEEDKAKTTFI
TPWGTFCYKVMPFGLKNLGATYQRAMVALFHDMMHKEIKVYV-----DDMIAKSKPGEDH
VQVLRKLFERLWKYKLKLNPAKYVFGAQSGKLLGFMVSNRGIEIDPSKVKAILDIGIPTT
VKEVRSLLGRLNYIARFICQLS
>tig00021394_arrow__1 [68897 69571] 
-DVGFIEVTQYPTWVANIVPVLKND------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00021399_arrow__1 [133941 134609] 
---GFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHMDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021401_arrow__1 [1753808 1754482] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00021420_arrow__1 [1346382 1345708] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021426_arrow__1 [768874 769545] 
--VGFIEVTQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVVVDSTARLELFSFMDGFSGYNQILMSEDDKEKTAFI
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMMHKEIEVYV-----DDMIAKTRRGKDH
VETLTKLFERLRKFKLRLNRVKCVFGASSGKLLGFIVSNKGIEIDPSKMKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00021433_arrow__1 [1069401 1068730] 
--VNFVEVAYYADWIANVIPMMKKD------------------GRVRVCIGYH-------
-----DLNRANP-KDNFPLSHIDVLVDSTTRFKLFSFMDSFSGYNQIQMREENRRKTSFI
IPWGTFRYKVMPFSLKNAGTTYQRAMVALFHDMMHNGIEVCI-----DDMIAKSRAGEDH
VASLRKLFEYLRKYQLRLNPTKCILRAKSEKLLGFMVSSRGIKIDPFKVKAICDL-PPSS
VREVCSLLGRLNYVARFISQLS
>tig00021437_arrow__1 [1465514 1464843] 
--VGFIEAIPYADWIANIVLVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSIAGFELFSFRDGFSGYNQILMKEEDKAKTSFI
TPWGTFCY-VMPFGLKNAGATYQRAMVALFHNMMHKEIEIYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VKEVRSLLGRLNYIARFISQLS
>tig00021441_arrow__1 [139793 139119] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGTTSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKEVRSLMGRLNYIARFISQLS
>tig00021443_arrow__1 [493054 492380] 
-EVGFIEVSQYSDWVANIVPVMKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKIKTSFT
TPWGLFHYKVMPFGLRNAGATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRRGENH
VETLTKLFDRLRKFKLRLNPAKCVFGATSGKLLGFIVSSKGIEIDPSKVKAICEVKPPRS
VKKVRSLMGKLNYIARFISQLS
>tig00021447_arrow__1 [300426 301097] 
--VGFIEVS-YSDWVANIVPVMKKD------------------G-VRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTVGFELFSFMDGFSSYNQILMNDEDEIKTSFT
TPWGSFHYKVMPFGLKNAMATYQRAMVTLFHDMMHEEIEVYV-----DDMIAKTRE-ENH
VETLTKLFVRLRKFKLRLNPAKCVFGATSGKLLEFIVNNKGIEIDPSKVKAICEVKPPKS
VKEVRSLMGKLNYIARFISQLS
>tig00021450_arrow__1 [441704 441033] 
--VGFIEAIPYADWIANIVPVMKKD------------------GKIRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFI
TPWGTFCYRVMPFGLKNAGATYQRAMVALFHDMMHKEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVNNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00062549_arrow__1 [51604 52020] 
------------------------------------------------------------
---------ASP-KDDFPMPHIDVLVDSTVGFELFLFMDGFSGYNQILLKEEDKAKTSFI
MSWGTFCYKVMPFSLKNAGATYQRVMVALSHNMMHKEIEVYV-----DDMIAKSKSGEDH
VQVLRKLFERLRKYKLKLNPAKYVFGA-SGKFFG--------------------------
----------------------
>tig00062623_arrow__1 [362370 361696] 
-DVGFIEVTQYPTWVANIVPVLKKD------------------GRVRICVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHKEIEVYV-----DYMIAKTRHGEDH
VETLTKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00062625_arrow__1 [898492 897818] 
-DVGFIEVTQYATWVSNIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLINSTAGFELFSLMNGFLGYN-ILMNEEDKEKMAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTVFHDMMHKEIEVYV-----DDMIAKTCRGENH
VEILMKLFDRLQKFRLRLNPAKCVFGASSGKLLGFIVSNKGIKIDPSKVKAICELKPPAT
VKEVQSLMGRLNYIARFISQLS
>tig00062629_arrow__1 [352682 352008] 
-DVGFIEITQYPTWVANIVPVLKKD------------------GRVRVCVDYR-------
-----DLNKASP-KDEFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMITLFHDMIHKEIEVYV-----DDMIAKTRHGEDH
VETLAKLFERLRKFKLRLNPAKCVFGASSGKLLGFIVSNKGIEIDPSKVKAICELKPPAT
VKEVRGLMGRLNYIARFISQLS
>tig00062631_arrow__1 [3089965 3090636] 
--VGFIEAIPYADWIANIVPVMKKD------------------GKILVCVDYR-------
-----DLNKASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKVKTSFI
TPWGTFCYRVMPFGLKNAGATYQRAMVALFHDMMHEEIEVYV-----DDMIAKSRPGEDH
ILVLRKLFERLRKYKLRLNPNKCVFGTRSGKLLGFVVSNRGIEIDPAKIKAIREIRTPTT
VREVRSLLGRLNYIARFISQLS
>tig00062634_arrow__1 [3329647 3330321] 
-EVGFIEVTQYPTWVANIVPVLKKD------------------GRVRICVDYR-------
-----DLNKASP-KDDFSLPHIDVLVDSTVRFELFSFMDGFSGYNQILMNEEDKEKTAFT
TPWGVFHYKVMPFGLKNAGATYQRAMVTLFHDMMHREIEVYV-----DDMIAKTRHREDH
VETLTKLFERLRKFKLRLNPAKCVFGVSSGKLLGFIVSNKGIEIDPSKVKAICELKPPTT
VKEVRGLMGRLNYIARFISQLS
>tig00062639_arrow__1 [681036 681701] 
----FIKVVPYADWIANVVPVMKKE------------------GKVRICVDYR-------
-----DLNRASP-KDDFPLPHIDVLVDSTAGFELFSFMDGFSGYNQILMKEEDKAKTSFI
TP-GTFCYKVMPFGLKNAGATYQRAMVALFHDMIHKEIEVYV-----DDMIAKSRHSEDH
ILVLKKLFERLRKYRLGLNPAKCVFGARSGKLLGFVVASRGIEIDPSKIKAIRDIRIPSM
VNEVRSLLGRLNYIARFTSQLS
>RT_Bagy-2
LEAGIIYPVAHSDWVSPVHCVPKKGGITVVPNDKNELIPHRIVTGYRMVIDFR-------
-----KLNKATR-KDHYPLPFIDKMLERLSNTHF-CFLDGYSGFSQISAAQSDQEKTTFT
CPFGTFAYRRMAFGLCNAPATFQRCMMAISSDFCEKIIEVFM-----DDFSVYGSSFDDY
LSNLDRVLQRCKDTNLVLNWEKCHFMVNEGIVLGHKISAKGIEVDKAKVDAIEKMPCPID
IRGIRSFLGHAGFYRRFIKDFS
>RT_Diaspora
LQAGIIYPISDSQWVSPVQVVPKKTGLTVIKNEKEELIPTRVQNNWRVCIHYR-------
-----RLNQVTK-KDHFPLPFIDQILECLAGKSHYCFLDGFSGYMQITIALEDQEKTTFT
CLFGTFAYRRMSFGLCNAPGTFQRCMISIFSDFLENCIEEFM-----DDFTVYGSSFDGC
LDSLEKVLNRRIETNLVLNFEKCHFMVEQGIVLGHIISNKGIEVDPAKISVISQLPYPSC
VE-VRSFLGHAGFYRCFIRDFS
>RT_Athila4-1
LDAGVIYPISDSTWVSPVHCVPKKGGMTVVKNEKDELIPTRTITGHRMCIDYR-------
-----KLNAASR-KDHFPLPFIDQMLERLANHPYYCFLDGYSGFFQIPIHPNDQEKTTFT
CPYGTFAYKRMPFGLCNAPATFQRCMTSIFSDLIEEMVEVFM-----DDFSVYGPSFSSC
LLNLGRVLTRCEETNLVLNWEKCHFMVKEGIVLDHKISEKGIEVDKGKVEVMMQLQPPKT
VKDIRSFLGHAGFYRRFIKDFA
>RT_Cyclops-2
LDARMIYPISDSPWVSPVHVVPKKGGNTVIRNDKDELIPTKVATGWRMCIEYR-------
-----RLNTATR-KDHFPLPFMDQMLERLSGQQYYCFLDGYSGYNQIAVDPADH-KTAFT
CPFGVFAYRKMSFGLCNAPTTFQRCVQAIFADLNEKTMEVFM-----DDFSVFGVSFSLC
LANLKTVLERCVKTNLVLNW-KCHFMVTEGIVLGHKVSSRGLEVDRAKVEVIEKLPPPVN
VKGIRSFLGHVGFYRHFIKEFS
>RT_Calypso5-1
VARSRPHPISDSAWVSPVQVVLKKGGMTVIKNDKDELISTRTVTGWRMCIDYR-------
-----KLNNATW-KDHYPLPFMDHMLERLARQSYYCFLDGYSSYN-IAIDIKDQEKTTFT
FPFGVFAYRCMPFGLCNALATFQRCMMAIFSDMVEKCIEVFM-----DDFSVFGPSFDGC
LSNLERVF-RCEESNLVLNWEKCHFMVQEGIVLGHKISVRGIEVDKVKIDVIEKLPPPMN
VKRMRSFLGHDGFYR-LIKDFS
>RT_Ogre
WDAGFLAVTSYPPWMANIVPVPKKD------------------GKVRMCVDYR-------
-----DLNRASP-KDDFPLPHIDVLVDNTAQSSVFSFMDGFSGYNQIKMAPEDMEKTTFI
TPWGTFCYKVMPFGLKNAGATYQRAMTTLFHDMMHKEIEVYV-----DDMIAKSQTEEEH
LVNLQKLFDRLRKFKLRLNPNKCTFGVRSGKLLGFIVSEKGIEVDPAKVKAIQEMPEPKT
EKQVRGFLGRLNYIARFISHLT
>RT_Tat4-1
LGAGSIVEVKYPEWLANPVVVKKKN------------------GKLRVCIDFT-------
-----DLNKACP-KDSFPLPHIDRMVEATTGNELLSFMDAFSGYNQIPMHKDDQEKTSFI
TDRGTYCYKVMPFGLKNAGARYQRLVNQMFAPQLGKTMEVYI-----DDMLVKSKKSADH
IEHLTACFETLNKYNMKLNPAKCSFGVTSGEFLGYIVTKRGIEANPKQIQAILDLKSPRN
KKEVQRLTGRIAALNIFIARST
>RT_Tft2
LKIGSIREVQYPDWLANTVVVKKKN------------------GKRIVCIDFT-------
-----DLNKACP-KDSFPLPHIDNLVESTAGNELLSFMDALSGYNQIMMNPEDQEKTSFI
TDRGIYCYKVMPFGLKNAGATYQRLVNKMFNEHLGKTMEVYI-----DYMLVKSLKKEDH
VKHLEECFAILNQYQMKLNPAKCTFGVPSGEFLSYIVRKRGIEANPNQINAFLNMSSPKN
FKEVQRLTGRIAALNRFISRST
>RT_RetroSor1
LDAKVIREVIYPEWLANVVLVPKKN------------------GKMRMCIDFT-------
-----DLNKACV-KDSFPLPRIDTSVDKAAGCQRFSLLDCFSGYHQIWLKKEDEGKASFT
TPFGTYCYTRMPEGLKNAGATFSRMMGKVLGSQLQRNIIAYV-----DDVVVMSKRKEDH
IKDLQETFVNLRSAGLKLNPEKCVFGVSKGKMLGYIISSEGIRANPDKTKAIMSMAEPSN
KKEVQRLTGRIAALNRFISRSA
>RT_Cinful-1
LSAGVIREVKYPEWLANTVMVKKAN------------------GKWRMCIDFT-------
-----DLNKACP-KDEFPLPRIDSLVDATASSELMSLLDCYSGYHQIWMKREDEPKTSFI
TPSGTYCYLRMPEGLKNAGGSFSRMTAKVLQSQIGRNVLTYV-----DDIIVKSTKQENH
IADLQETFASFRQAGLKLNPEKCVFGVKKGKFLGCLVSTKGIEANPSKIEAILRMEPPTT
KKGAQRLTGRLASLNRFISRSA
>RT_B1147A04.5
-LVSFLRAN------ADVFAWRPADM----------------PGVPREVIEHRLAVRSGA
RPVRQKVRRQAP--------------------ERQAFIR--SGYHQIRMAREDEEKTAFI
TPIGTYCYTTMPFGLKNAGPTFQRTTRISLGSQIGRNVEAYV-----DDLVVKTRNQETL
LSDLAETFESLRSARIKLNPDKCVFGVPAGKLLGFLVSARGIEANPEKIRAIERMRPPSK
LRDMQCVTGCMAALSRFISRLG
>RT_Grande1-4
VAAGFIREVLHPEWLPTLFLYSKRI------------------KWIGACASTI-------
-----LISTNTVRRDPFGLPRIDQVVDSTAGCSMLSFLDCYSWYHQISLAKEDEEKTAFI
TPFGAFCYTSMSFGLKNGRATYQRAIQTCLANHWGKRVEAYV-----DDVVIKIENSENF
IEDLQLVFNSLRRYRWKLNPEKCVFGVPAGKLLGFIVSHRGIEANPDKIEAIMKMEAPRS
QKKVQRLTGCMAALSRFISRLG
>RT_RIRE2
LAAGFIKEVLHPDWLANPVLVRKKT------------------GQWRMCVDYT-------
-----DLNKSCP-KDPFGLPRIDQVVDSTAGCELLSFLDCYSGYHQIRLKESDCLKTSFI
TPFGAYCYVTMPFGLKNAGATYQRMIQRCFSTQIGRNVEAYV-----DDVVVKTKQKDDL
ISDLEETFASIRAFRMKLNPEKCTFGVPSGKLLGFMVSHRGIQANPEKVTAILNMKPPST
QKDVQKLTGCMAALSRFVSRLG
>RT_CRM
LDKGYVRESLSPCAV-PVILVPKKD------------------GTWRMCVDCR-------
-----AINNITI-RYRHPIPRLDDMLDELSGAIVFSKVDLRSGYHQIRMKLGDEWKTAFK
TKFGLYEWLVMPFGLTNAPSTFMRLMNEVLRAFIGKFVVVYF-----DDILIYSKSMDEH
VDHMRAVFNALRDARLFGNLEKCTFCTDRVSFLGYVVTPQGIEVDQAKVEAIHGWPMPKT
ITQVRSFLGLAGFYRRFVKDFS
